// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8hu30rQyATIBmPLUzrJerFSuXu_DHBps',
    appId: '1:393481378538:web:d6c4d5c8d86f2d829e9593',
    messagingSenderId: '393481378538',
    projectId: 'medical-block-app-c8f02',
    authDomain: 'medical-block-app-c8f02.firebaseapp.com',
    storageBucket: 'medical-block-app-c8f02.appspot.com',
    measurementId: 'G-0MN8PTLKF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY1pT3t04PRN0hQtrWGy_1ONt1KjGgRIk',
    appId: '1:393481378538:android:d1eb470baf88da7c9e9593',
    messagingSenderId: '393481378538',
    projectId: 'medical-block-app-c8f02',
    storageBucket: 'medical-block-app-c8f02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYBU9LQFBpBwbHC2PxjvMefSsji89PmLo',
    appId: '1:393481378538:ios:10ad93cf36a6e5ec9e9593',
    messagingSenderId: '393481378538',
    projectId: 'medical-block-app-c8f02',
    storageBucket: 'medical-block-app-c8f02.appspot.com',
    iosBundleId: 'com.example.portfolioFlutterBlockchainMedicalWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYBU9LQFBpBwbHC2PxjvMefSsji89PmLo',
    appId: '1:393481378538:ios:10ad93cf36a6e5ec9e9593',
    messagingSenderId: '393481378538',
    projectId: 'medical-block-app-c8f02',
    storageBucket: 'medical-block-app-c8f02.appspot.com',
    iosBundleId: 'com.example.portfolioFlutterBlockchainMedicalWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8hu30rQyATIBmPLUzrJerFSuXu_DHBps',
    appId: '1:393481378538:web:99e28656b9abdd819e9593',
    messagingSenderId: '393481378538',
    projectId: 'medical-block-app-c8f02',
    authDomain: 'medical-block-app-c8f02.firebaseapp.com',
    storageBucket: 'medical-block-app-c8f02.appspot.com',
    measurementId: 'G-1Z3VX2N33V',
  );

}