// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-1_lLqec7YdAwSQnIqLOxqRfP8006F1M',
    appId: '1:842075101905:web:03619e3da0b6afb55943f0',
    messagingSenderId: '842075101905',
    projectId: 'medical-block-app',
    authDomain: 'medical-block-app.firebaseapp.com',
    storageBucket: 'medical-block-app.appspot.com',
    measurementId: 'G-RY53Q3L2SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASRnVAiAfDVJ5qDBlyiaBk1UJEbC-zCqw',
    appId: '1:842075101905:android:4ad532582a84e9005943f0',
    messagingSenderId: '842075101905',
    projectId: 'medical-block-app',
    storageBucket: 'medical-block-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo7rZaYjQlK8vf1NRQGdF6Wrmaz-5IRro',
    appId: '1:842075101905:ios:37b34fd38b95d81b5943f0',
    messagingSenderId: '842075101905',
    projectId: 'medical-block-app',
    storageBucket: 'medical-block-app.appspot.com',
    iosBundleId: 'com.example.portfolioFlutterBlockchainMedicalWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo7rZaYjQlK8vf1NRQGdF6Wrmaz-5IRro',
    appId: '1:842075101905:ios:37b34fd38b95d81b5943f0',
    messagingSenderId: '842075101905',
    projectId: 'medical-block-app',
    storageBucket: 'medical-block-app.appspot.com',
    iosBundleId: 'com.example.portfolioFlutterBlockchainMedicalWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-1_lLqec7YdAwSQnIqLOxqRfP8006F1M',
    appId: '1:842075101905:web:c280a5b5b62c53fe5943f0',
    messagingSenderId: '842075101905',
    projectId: 'medical-block-app',
    authDomain: 'medical-block-app.firebaseapp.com',
    storageBucket: 'medical-block-app.appspot.com',
    measurementId: 'G-PYMHYJNE1N',
  );

}